version: "3"
services:
  mvc:
    image: justcallmenines/proj2mvc:0.2
    ports:
      - "5000:80"
    networks:
      - net
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ServiceUris__api: "http://api"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  api:
    image: justcallmenines/proj2api:0.1
    ports:
      - "5002:80"
    networks:
      - net
    env_file: secrets.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  angular:
    image: justcallmenines/proj2angular:0.1
    ports:
      - "5001:80"
    networks:
      - net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  net: